name: Update Live M3U

on:
  schedule:
    # Chạy mỗi ngày lúc 01:00 UTC (có thể đổi)
    - cron: '25 */2 * * *'
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests rapidfuzz

      - name: Run script to generate Stream_live.m3u
        run: python generate_live_m3u.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Stream_live.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update Stream_live.m3u"
          git push
